###
POST http://localhost:3000/auth/login HTTP/1.1
content-type: application/json

{
    "username": "test",
    "password": "test"
}

###
POST http://localhost:3000/auth/register HTTP/1.1
content-type: application/json

{
    "username": "test1",
    "password": "test"
}