version: '3.8'
services:
  backend:
    build:
      context: ..
      dockerfile: infra/dockerfiles/backend.dockerfile
    ports:
      - '3000:3000'
    environment:
      PORT: 3000
  frontend:
    build:
      context: ..
      dockerfile: infra/dockerfiles/frontend.dockerfile
    ports:
      - '80:80'
    depends_on:
      - backend
