version: '3.8'
services:
  backend:
    build:
      context: ..
      dockerfile: infra/dockerfiles/backend.dockerfile
    ports:
      - '3000:3000'
    environment:
      PORT: 3000
    depends_on:
      - database
  frontend:
    build:
      context: ..
      dockerfile: infra/dockerfiles/frontend.dockerfile
    ports:
      - '8080:8080'
    depends_on:
      - backend
  database:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres 
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=inventorydb
      - DATABASE_HOST=localhost
    ports:
      - '5432:5432'